{% set name = "forest" %}
{% set version = "0.15.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/informatics-lab/forest/archive/v{{ version }}.tar.gz
  sha256: 018b36dab7c2726bcc7ee215ce2fca307d98546d311b60d59eb0390b14104011

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<35]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - iris
    - bokeh =1.4
    - datashader
    - xarray
    - dataclasses # [py36]

test:
  imports:
    - forest

about:
  home: http://github.com/informatics-lab/forest
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Forecast and observation research and evaluation survey tool
  description: |
    FOREST is a web viewer built on top of the bokeh Python package
    designed to offer a fast and simple way to explore geophysical
    data sets
  doc_url: http://forest-informaticslab.readthedocs.io/

extra:
  recipe-maintainers:
    - andrewgryan
