{% set name = "forest" %}
{% set version = "0.16.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/informatics-lab/forest/archive/v{{ version }}.tar.gz
  sha256: 12e1078a9217ee50e87a1799e8b92844be66df034c39732ba132ff6dfee64ab4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<35]

requirements:
  host:
    - python
    - pip
  build:
    - nodejs >=10.13
  run:
    - python
    - iris
    - bokeh >=2.0.2
    - datashader
    - xarray
    - dataclasses  # [py36]

test:
  imports:
    - forest

about:
  home: http://github.com/informatics-lab/forest
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Forecast and observation research and evaluation survey tool
  description: |
    FOREST is a web viewer built on top of the bokeh Python package
    designed to offer a fast and simple way to explore geophysical
    data sets
  doc_url: http://forest-informaticslab.readthedocs.io/

extra:
  recipe-maintainers:
    - andrewgryan
