{% set name = "forest" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/informatics-lab/forest/archive/v{{ version }}.tar.gz
  sha256: eba1ae1a50feb38ab7225df480993a7f02549283c06a74c768e3ee34099a70af

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<35]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - iris
    - bokeh

test:
  imports:
    - forest

about:
  home: http://github.com/informatics-lab/forest
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Forecast and observation research and evaluation survey tool'
  description: |
    FOREST is a web viewer built on top of the bokeh Python package
    designed to offer a fast and simple way to explore geophysical
    data sets
  doc_url: http://forest-informaticslab.readthedocs.io/

extra:
  recipe-maintainers:
    - andrewgryan
