{% set name = "forest" %}
{% set version = "0.15.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/informatics-lab/forest/archive/v{{ version }}.tar.gz
  sha256: 0235c323c8218b3cf477983619cc0ff77104911a58f58dd63ef6aed1becb0f81

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<35]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - iris
    - bokeh=1.4
    - datashader
    - xarray

test:
  imports:
    - forest

about:
  home: http://github.com/informatics-lab/forest
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Forecast and observation research and evaluation survey tool
  description: |
    FOREST is a web viewer built on top of the bokeh Python package
    designed to offer a fast and simple way to explore geophysical
    data sets
  doc_url: http://forest-informaticslab.readthedocs.io/

extra:
  recipe-maintainers:
    - andrewgryan
