travis:
  secure:
    BINSTAR_TOKEN: TNF3EVu+2t/OYbGK3zzU5270NzI4n71BFpJabAcw+eUFooF6k0sNFXSUf47k8NoI/JtFQGnRamD84wk0N5reqOWwoMdAV09Z9DUqFH02RMQ5PA3QMV3cS+715REE9JCj4lfsDnunCbue/56xgdwy9H7l8aM4meyjl1Uzf0MWz+cfNmM0YsOUSjLVL4bNpr62YSFcYHNIhKN3qvCC8Rul2owaiEfmZOUAmIle4+D3RwtTBmMGanME12wSlXquEVYyCXkPv8kMhX4ygetzfgnrkHMMYEewi8pCv9B6YBzFr/7iC7QaVBWjU9T5U1a7LsfX2b1EmaD7zyl8tucLn0ojaQRkFsG+/5FN0iz73zdWQYLjqu6fXm96qdK9uGYQ5viM5PwLZDaigozKYwIsjNVLcykWDWYko+94MMacJjtNB7mL+sMBYzQ4ausSUfKlJ4LdpSpaRbW1bLYvO8qimCqdyVJ8VETv5c8iWqyz8zhDd3Cqsp/yQkL2xZBCz54R3ImZfRTF7zFRIBdGtiIwCLB/zaamfYw2Lvy7fCCacwVavB1JvttuQFhTYAQb6YMZ2uYHMpWjYHZihAaxgN5MbNgRIQw9le0VQjXndaE5jb/kZyHocItXeCpWyrqiPJpwDmZobPo+7E3lvPFsSrmzwhSfHyt6u8uOpNZfnrUWhjXkQgs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
